services:
  gateway:
    build: ./gateway
    environment:
      - PORT=8080
      - HMAC_SECRET=CHANGE_ME_DEV_SECRET
      - REVOCATIONS_PATH=/app/revocations.json
      - UPSTREAM_PROD=http://merchant:5000
      - UPSTREAM_SANDBOX=http://sandbox:5001
      - DEFAULT_ROUTE=sandbox   # sandbox | deny | prod
    ports:
      - "8080:8080"
    depends_on:
      - merchant
      - sandbox

  merchant:
    build: ./merchant
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    expose:
      - "5000"

  sandbox:
    build: ./sandbox
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
    expose:
      - "5001"